### ISSUE TITLE
Regulate term selection based on department

### ISSUE THREAD

**Issue by cxrvxxxx** [ArchonsDev/react-pointwatch-web#46]
In Employee dashboard, the terms to display should only be those applicable for their Department
![image](https://github.com/ArchonsDev/react-pointwatch-web/assets/35297070/896fc6f1-bd1d-4c22-95ae-74ac6e7db0f8)

In adding an SWTD, same rule applies.
![image](https://github.com/ArchonsDev/react-pointwatch-web/assets/35297070/c427017c-a46f-41eb-8a32-764859abcea0)

**Comment by cxrvxxxx** [comment]
This might also be applicable to staff/admin dashboards since it just renders the employee dashboard in a nested level

**Comment by mssjcksn** [comment]
Again, we don't have a set of fixed names for the terms after asking like twice or thrice? I kept asking over and over if we should follow how AIMS handles terms and receiving zero response about it hahahahahahahahahahahahahahahah

It's easier to check based on how the term is named and without the fixed set, we have to consider the variations ("1st Semester" and  "First Semester") and possible user errors (i.e. typos) for naming such term bc the PUT/DELETE methods are not implemented (⁠•⁠‿⁠•⁠)

**Comment by cxrvxxxx** [comment]
You have access to the term dates

**Comment by cxrvxxxx** [comment]
I can do it for you if you want.

**Comment by mssjcksn** [comment]
Access term dates and then what? Check if it's less than 5 months = semester??????
If that's the case, I'm supposed to
- Check if the dates entered are valid (more than 3 months, less than 5 months -- just an assumption tabangi kog huna2 tenks)
- Check if it's a mid year (less than 3 months prolly + what the hell is the minimum)
- Check if it's an academic year (more than 5 months) no?

Is there a way to add like some column or additional table (term id, department id/name) where the admin can just assign departments (since you also have that list in ur backend code) for a term?

for ex.
First/Second Semester
- [x] College
- [x] Senior High School
- [ ] Junior High School
- [ ] Elementary
- [ ] Administrative

Mid Year
- [x] College
- [x] Senior High School
- [x] Junior High School
- [x] Elementary
- [ ] Administrative

and all that jazz 🎺

**Comment by cxrvxxxx** [comment]
One option would be to add a discriminator property for the term: i.ie.
Term.type: "SEMESTER" | "YEAR"

**Comment by mssjcksn** [comment]
cant we at least edit the term at least name lang what if typo 😭

**Comment by cxrvxxxx** [comment]
Do check:
https://github.com/ArchonsDev/flask-pointwatch-api/commit/f60736836aa4c53a1e35be5267eeb2e11f4a8581

Also, unrelated but for socketio CORS:
https://github.com/ArchonsDev/flask-pointwatch-api/commit/57d8756c74cc299a386db8202cbda1135b505902

**Comment by mssjcksn** [comment]
This "is_sem" thing, does this mean I have to check if the term name contains a "Semester" word or starts with "Sem" and pass true?

**Comment by mssjcksn** [comment]
ok na?
![Screenshot 2024-05-21 135554](https://github.com/ArchonsDev/react-pointwatch-web/assets/62651994/ad4a5aa5-ab39-4575-bacb-c75644ff7c3e)
![Screenshot 2024-05-21 135632](https://github.com/ArchonsDev/react-pointwatch-web/assets/62651994/1db44e15-ca8e-44a7-be63-248ccd270818)
![Screenshot 2024-05-21 135510](https://github.com/ArchonsDev/react-pointwatch-web/assets/62651994/1ef77e40-4653-47d4-915d-3c5061064891)
